# app/Dockerfile
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/streamlit/streamlit-example.git .

COPY app /app
COPY /requirements-streamlit.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r /app/requirements.txt

EXPOSE 8501
ENV PYTHONPATH=/app

ENTRYPOINT ["streamlit","run"]
CMD ["app.py","--server.port=8501","--server.address=0.0.0.0"]